[2022-09-23 16:47:42,557] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: kag_to_gcs_dag.local_to_gcs_task manual__2022-09-23T16:39:46.298334+00:00 [queued]>
[2022-09-23 16:47:42,567] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: kag_to_gcs_dag.local_to_gcs_task manual__2022-09-23T16:39:46.298334+00:00 [queued]>
[2022-09-23 16:47:42,567] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-23 16:47:42,567] {taskinstance.py:1239} INFO - Starting attempt 4 of 5
[2022-09-23 16:47:42,567] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-23 16:47:42,578] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-09-23 16:39:46.298334+00:00
[2022-09-23 16:47:42,587] {standard_task_runner.py:52} INFO - Started process 767 to run task
[2022-09-23 16:47:42,591] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'kag_to_gcs_dag', 'local_to_gcs_task', 'manual__2022-09-23T16:39:46.298334+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/kag_to_gcs_dag.py', '--cfg-path', '/tmp/tmp9nxuscnu', '--error-file', '/tmp/tmpocxlowu_']
[2022-09-23 16:47:42,592] {standard_task_runner.py:77} INFO - Job 6: Subtask local_to_gcs_task
[2022-09-23 16:47:42,641] {logging_mixin.py:109} INFO - Running <TaskInstance: kag_to_gcs_dag.local_to_gcs_task manual__2022-09-23T16:39:46.298334+00:00 [running]> on host 2d41e074c0f7
[2022-09-23 16:47:42,691] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=kag_to_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-23T16:39:46.298334+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-23T16:39:46.298334+00:00
[2022-09-23 16:47:44,609] {logging_mixin.py:109} INFO - downloading amazon_reviews_us_Digital_Music_Purchase_v1_00.tsv
[2022-09-23 16:47:50,155] {logging_mixin.py:109} INFO - uploading amazon_reviews_us_Digital_Music_Purchase_v1_00.tsv
[2022-09-23 16:47:53,849] {logging_mixin.py:109} INFO - removing file amazon_reviews_us_Digital_Music_Purchase_v1_00.tsv
[2022-09-23 16:47:53,895] {logging_mixin.py:109} INFO - downloading amazon_reviews_us_Video_Games_v1_00.tsv
[2022-09-23 16:47:54,602] {logging_mixin.py:109} INFO - amazon_reviews_us_Video_Games_v1_00.tsv could not be found
[2022-09-23 16:47:54,602] {logging_mixin.py:109} INFO - removing file amazon_reviews_us_Video_Games_v1_00.tsv
[2022-09-23 16:47:54,602] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 62, in upload_to_gcs
    os.remove(f"{AIRFLOW_HOME}/{file_name}.zip")
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/amazon_reviews_us_Video_Games_v1_00.tsv.zip'
[2022-09-23 16:47:54,616] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=kag_to_gcs_dag, task_id=local_to_gcs_task, execution_date=20220923T163946, start_date=20220923T164742, end_date=20220923T164754
[2022-09-23 16:47:54,633] {standard_task_runner.py:92} ERROR - Failed to execute job 6 for task local_to_gcs_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 62, in upload_to_gcs
    os.remove(f"{AIRFLOW_HOME}/{file_name}.zip")
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/amazon_reviews_us_Video_Games_v1_00.tsv.zip'
[2022-09-23 16:47:54,664] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-09-23 16:47:54,690] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
